### ISSUE TITLE
New feature: Please add unzip to cli container.

### ISSUE THREAD

**Issue by michael-molchanov** [blinkreaction/docker-drupal-cli#2]
Hi team

Please add unzip to cli container. Required by drush make when trying to build Pfizer platform. Without unzip it's impossible to download js libraries to platform.

http://drupal.stackexchange.com/questions/96096/drush-make-command-error-when-unzipping-superfish-module-library

Thank you

**Comment by lmakarov** [comment]
Added in 503a416ac565777f7fe39c24f4821103febef19a
Released in [v1.0.0](https://github.com/blinkreaction/docker-drupal-cli/releases/tag/v1.0.0)
