### ISSUE TITLE
Feature request: PHP_CodeSniffer in CLI

### ISSUE THREAD

**Issue by dashav** [blinkreaction/docker-drupal-cli#5]
Need to add PHP_CodeSniffer and PHPCompatibility (optional) to run code analysis.

**Comment by lmakarov** [comment]
Added in dc45e33fc0e236e4c3d961ab760c6eb2712d85f8
Released in [v1.0.0](https://github.com/blinkreaction/docker-drupal-cli/releases/tag/v1.0.0)
